Installing binaries separately
LNP-BP/nodes pull request #4
Opened 2022-07-18 12:35 UTC by adambor

Creating PR in response to bug raised here: https://github.com/LNP-BP/nodes/discussions/2#discussioncomment-3171090

2022-07-30 16:04 UTC, dr-orlovsky requested changes
Thank you for typing all of that!

Please see my comments - we need to make the second block exactly the same as the first one (currently it misses `--all-features`). I also used this opportunity to pub the latest released version numbers where appropriate.

2022-07-30 16:04 UTC, dr-orlovsky commented on contrib/demo-rgb.sh
> +# cargo +nightly -Z bindeps install lnpbp_nodes --version 0.8.0-rc.1
```suggestion
# cargo +nightly -Z bindeps install lnpbp_nodes --version 0.8.0-rc.1
```

2022-07-30 16:04 UTC, dr-orlovsky commented on contrib/demo-rgb.sh
>  # This installs all 4 LNP/BP nodes at onc
```suggestion
```

2022-07-30 16:04 UTC, dr-orlovsky commented on contrib/demo-rgb.sh
> +cargo install bp_node --version "0.8.0-alpha.2"
Here and below: `--all-features` is missed everywhere. Probably it will be easier to copy-paste the lines above (they jave to be the same).

2022-09-11 02:15 UTC, cryptoquick commented
@dr-orlovsky This issue can be closed now that #11 is merged.

2022-09-11 08:55 UTC, closed without merging